# Generated by Django 5.2.17 on 2026-08-23 16:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(blank=True, null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=30)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_logs',
            },
        ),
        migrations.CreateModel(
            name='LlmCallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField()),
                ('call_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('raw_response', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'llm_call_logs',
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField()),
                ('prescription_id', models.UUIDField()),
                ('patient_email', models.EmailField(max_length=254)),
                ('medication_name', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medication_reminders',
            },
        ),
    ]
